//
//  google-find-my-tools-go - Go reimplementation of GoogleFindMyTools
//  Copyright © 2024 Leon Böttger. All rights reserved.
//  Copyright © 2024 Marcel Heers <marcel@heers.it>
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: findhub/common.proto

package findhub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_SEMANTIC     Status = 0
	Status_LAST_KNOWN   Status = 1
	Status_CROWDSOURCED Status = 2
	Status_AGGREGATED   Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "SEMANTIC",
		1: "LAST_KNOWN",
		2: "CROWDSOURCED",
		3: "AGGREGATED",
	}
	Status_value = map[string]int32{
		"SEMANTIC":     0,
		"LAST_KNOWN":   1,
		"CROWDSOURCED": 2,
		"AGGREGATED":   3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_findhub_common_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_findhub_common_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_findhub_common_proto_rawDescGZIP(), []int{0}
}

type Time struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seconds       uint32                 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos         uint32                 `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Time) Reset() {
	*x = Time{}
	mi := &file_findhub_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Time) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Time) ProtoMessage() {}

func (x *Time) ProtoReflect() protoreflect.Message {
	mi := &file_findhub_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Time.ProtoReflect.Descriptor instead.
func (*Time) Descriptor() ([]byte, []int) {
	return file_findhub_common_proto_rawDescGZIP(), []int{0}
}

func (x *Time) GetSeconds() uint32 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Time) GetNanos() uint32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

type LocationReport struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SemanticLocation *SemanticLocation      `protobuf:"bytes,5,opt,name=semanticLocation,proto3" json:"semanticLocation,omitempty"`
	GeoLocation      *GeoLocation           `protobuf:"bytes,10,opt,name=geoLocation,proto3" json:"geoLocation,omitempty"`
	Status           Status                 `protobuf:"varint,11,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LocationReport) Reset() {
	*x = LocationReport{}
	mi := &file_findhub_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationReport) ProtoMessage() {}

func (x *LocationReport) ProtoReflect() protoreflect.Message {
	mi := &file_findhub_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationReport.ProtoReflect.Descriptor instead.
func (*LocationReport) Descriptor() ([]byte, []int) {
	return file_findhub_common_proto_rawDescGZIP(), []int{1}
}

func (x *LocationReport) GetSemanticLocation() *SemanticLocation {
	if x != nil {
		return x.SemanticLocation
	}
	return nil
}

func (x *LocationReport) GetGeoLocation() *GeoLocation {
	if x != nil {
		return x.GeoLocation
	}
	return nil
}

func (x *LocationReport) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_SEMANTIC
}

type SemanticLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationName  string                 `protobuf:"bytes,1,opt,name=locationName,proto3" json:"locationName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticLocation) Reset() {
	*x = SemanticLocation{}
	mi := &file_findhub_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticLocation) ProtoMessage() {}

func (x *SemanticLocation) ProtoReflect() protoreflect.Message {
	mi := &file_findhub_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticLocation.ProtoReflect.Descriptor instead.
func (*SemanticLocation) Descriptor() ([]byte, []int) {
	return file_findhub_common_proto_rawDescGZIP(), []int{2}
}

func (x *SemanticLocation) GetLocationName() string {
	if x != nil {
		return x.LocationName
	}
	return ""
}

type GeoLocation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EncryptedReport  *EncryptedReport       `protobuf:"bytes,1,opt,name=encryptedReport,proto3" json:"encryptedReport,omitempty"`
	DeviceTimeOffset uint32                 `protobuf:"varint,2,opt,name=deviceTimeOffset,proto3" json:"deviceTimeOffset,omitempty"`
	Accuracy         float32                `protobuf:"fixed32,3,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GeoLocation) Reset() {
	*x = GeoLocation{}
	mi := &file_findhub_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoLocation) ProtoMessage() {}

func (x *GeoLocation) ProtoReflect() protoreflect.Message {
	mi := &file_findhub_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoLocation.ProtoReflect.Descriptor instead.
func (*GeoLocation) Descriptor() ([]byte, []int) {
	return file_findhub_common_proto_rawDescGZIP(), []int{3}
}

func (x *GeoLocation) GetEncryptedReport() *EncryptedReport {
	if x != nil {
		return x.EncryptedReport
	}
	return nil
}

func (x *GeoLocation) GetDeviceTimeOffset() uint32 {
	if x != nil {
		return x.DeviceTimeOffset
	}
	return 0
}

func (x *GeoLocation) GetAccuracy() float32 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

type EncryptedReport struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PublicKeyRandom   []byte                 `protobuf:"bytes,1,opt,name=publicKeyRandom,proto3" json:"publicKeyRandom,omitempty"`
	EncryptedLocation []byte                 `protobuf:"bytes,2,opt,name=encryptedLocation,proto3" json:"encryptedLocation,omitempty"`
	IsOwnReport       bool                   `protobuf:"varint,3,opt,name=isOwnReport,proto3" json:"isOwnReport,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EncryptedReport) Reset() {
	*x = EncryptedReport{}
	mi := &file_findhub_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedReport) ProtoMessage() {}

func (x *EncryptedReport) ProtoReflect() protoreflect.Message {
	mi := &file_findhub_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedReport.ProtoReflect.Descriptor instead.
func (*EncryptedReport) Descriptor() ([]byte, []int) {
	return file_findhub_common_proto_rawDescGZIP(), []int{4}
}

func (x *EncryptedReport) GetPublicKeyRandom() []byte {
	if x != nil {
		return x.PublicKeyRandom
	}
	return nil
}

func (x *EncryptedReport) GetEncryptedLocation() []byte {
	if x != nil {
		return x.EncryptedLocation
	}
	return nil
}

func (x *EncryptedReport) GetIsOwnReport() bool {
	if x != nil {
		return x.IsOwnReport
	}
	return false
}

type GetEidInfoForE2EeDevicesRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OwnerKeyVersion    int32                  `protobuf:"varint,1,opt,name=ownerKeyVersion,proto3" json:"ownerKeyVersion,omitempty"`
	HasOwnerKeyVersion bool                   `protobuf:"varint,2,opt,name=hasOwnerKeyVersion,proto3" json:"hasOwnerKeyVersion,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetEidInfoForE2EeDevicesRequest) Reset() {
	*x = GetEidInfoForE2EeDevicesRequest{}
	mi := &file_findhub_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEidInfoForE2EeDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEidInfoForE2EeDevicesRequest) ProtoMessage() {}

func (x *GetEidInfoForE2EeDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findhub_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEidInfoForE2EeDevicesRequest.ProtoReflect.Descriptor instead.
func (*GetEidInfoForE2EeDevicesRequest) Descriptor() ([]byte, []int) {
	return file_findhub_common_proto_rawDescGZIP(), []int{5}
}

func (x *GetEidInfoForE2EeDevicesRequest) GetOwnerKeyVersion() int32 {
	if x != nil {
		return x.OwnerKeyVersion
	}
	return 0
}

func (x *GetEidInfoForE2EeDevicesRequest) GetHasOwnerKeyVersion() bool {
	if x != nil {
		return x.HasOwnerKeyVersion
	}
	return false
}

var File_findhub_common_proto protoreflect.FileDescriptor

const file_findhub_common_proto_rawDesc = "" +
	"\n" +
	"\x14findhub/common.proto\"6\n" +
	"\x04Time\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\rR\aseconds\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\rR\x05nanos\"\xa0\x01\n" +
	"\x0eLocationReport\x12=\n" +
	"\x10semanticLocation\x18\x05 \x01(\v2\x11.SemanticLocationR\x10semanticLocation\x12.\n" +
	"\vgeoLocation\x18\n" +
	" \x01(\v2\f.GeoLocationR\vgeoLocation\x12\x1f\n" +
	"\x06status\x18\v \x01(\x0e2\a.StatusR\x06status\"6\n" +
	"\x10SemanticLocation\x12\"\n" +
	"\flocationName\x18\x01 \x01(\tR\flocationName\"\x91\x01\n" +
	"\vGeoLocation\x12:\n" +
	"\x0fencryptedReport\x18\x01 \x01(\v2\x10.EncryptedReportR\x0fencryptedReport\x12*\n" +
	"\x10deviceTimeOffset\x18\x02 \x01(\rR\x10deviceTimeOffset\x12\x1a\n" +
	"\baccuracy\x18\x03 \x01(\x02R\baccuracy\"\x8b\x01\n" +
	"\x0fEncryptedReport\x12(\n" +
	"\x0fpublicKeyRandom\x18\x01 \x01(\fR\x0fpublicKeyRandom\x12,\n" +
	"\x11encryptedLocation\x18\x02 \x01(\fR\x11encryptedLocation\x12 \n" +
	"\visOwnReport\x18\x03 \x01(\bR\visOwnReport\"{\n" +
	"\x1fGetEidInfoForE2eeDevicesRequest\x12(\n" +
	"\x0fownerKeyVersion\x18\x01 \x01(\x05R\x0fownerKeyVersion\x12.\n" +
	"\x12hasOwnerKeyVersion\x18\x02 \x01(\bR\x12hasOwnerKeyVersion*H\n" +
	"\x06Status\x12\f\n" +
	"\bSEMANTIC\x10\x00\x12\x0e\n" +
	"\n" +
	"LAST_KNOWN\x10\x01\x12\x10\n" +
	"\fCROWDSOURCED\x10\x02\x12\x0e\n" +
	"\n" +
	"AGGREGATED\x10\x03BRZPgithub.com/mheers/google-find-my-tools-go/pkg/googlefindmy/proto/findhub;findhubb\x06proto3"

var (
	file_findhub_common_proto_rawDescOnce sync.Once
	file_findhub_common_proto_rawDescData []byte
)

func file_findhub_common_proto_rawDescGZIP() []byte {
	file_findhub_common_proto_rawDescOnce.Do(func() {
		file_findhub_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_findhub_common_proto_rawDesc), len(file_findhub_common_proto_rawDesc)))
	})
	return file_findhub_common_proto_rawDescData
}

var file_findhub_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_findhub_common_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_findhub_common_proto_goTypes = []any{
	(Status)(0),                             // 0: Status
	(*Time)(nil),                            // 1: Time
	(*LocationReport)(nil),                  // 2: LocationReport
	(*SemanticLocation)(nil),                // 3: SemanticLocation
	(*GeoLocation)(nil),                     // 4: GeoLocation
	(*EncryptedReport)(nil),                 // 5: EncryptedReport
	(*GetEidInfoForE2EeDevicesRequest)(nil), // 6: GetEidInfoForE2eeDevicesRequest
}
var file_findhub_common_proto_depIdxs = []int32{
	3, // 0: LocationReport.semanticLocation:type_name -> SemanticLocation
	4, // 1: LocationReport.geoLocation:type_name -> GeoLocation
	0, // 2: LocationReport.status:type_name -> Status
	5, // 3: GeoLocation.encryptedReport:type_name -> EncryptedReport
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_findhub_common_proto_init() }
func file_findhub_common_proto_init() {
	if File_findhub_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_findhub_common_proto_rawDesc), len(file_findhub_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_findhub_common_proto_goTypes,
		DependencyIndexes: file_findhub_common_proto_depIdxs,
		EnumInfos:         file_findhub_common_proto_enumTypes,
		MessageInfos:      file_findhub_common_proto_msgTypes,
	}.Build()
	File_findhub_common_proto = out.File
	file_findhub_common_proto_goTypes = nil
	file_findhub_common_proto_depIdxs = nil
}
