//
//  google-find-my-tools-go - Go reimplementation of GoogleFindMyTools
//  Copyright © 2024 Leon Böttger. All rights reserved.
//  Copyright © 2024 Marcel Heers <marcel@heers.it>
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: findhub/locationreportupload.proto

package findhub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocationReportsUpload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Reports        []*Report              `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	ClientMetadata *ClientMetadata        `protobuf:"bytes,2,opt,name=clientMetadata,proto3" json:"clientMetadata,omitempty"`
	Random1        uint64                 `protobuf:"varint,3,opt,name=random1,proto3" json:"random1,omitempty"`
	Random2        uint64                 `protobuf:"varint,4,opt,name=random2,proto3" json:"random2,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LocationReportsUpload) Reset() {
	*x = LocationReportsUpload{}
	mi := &file_findhub_locationreportupload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationReportsUpload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationReportsUpload) ProtoMessage() {}

func (x *LocationReportsUpload) ProtoReflect() protoreflect.Message {
	mi := &file_findhub_locationreportupload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationReportsUpload.ProtoReflect.Descriptor instead.
func (*LocationReportsUpload) Descriptor() ([]byte, []int) {
	return file_findhub_locationreportupload_proto_rawDescGZIP(), []int{0}
}

func (x *LocationReportsUpload) GetReports() []*Report {
	if x != nil {
		return x.Reports
	}
	return nil
}

func (x *LocationReportsUpload) GetClientMetadata() *ClientMetadata {
	if x != nil {
		return x.ClientMetadata
	}
	return nil
}

func (x *LocationReportsUpload) GetRandom1() uint64 {
	if x != nil {
		return x.Random1
	}
	return 0
}

func (x *LocationReportsUpload) GetRandom2() uint64 {
	if x != nil {
		return x.Random2
	}
	return 0
}

type Report struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Advertisement *Advertisement         `protobuf:"bytes,1,opt,name=advertisement,proto3" json:"advertisement,omitempty"`
	Time          *Time                  `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	Location      *LocationReport        `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_findhub_locationreportupload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_findhub_locationreportupload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_findhub_locationreportupload_proto_rawDescGZIP(), []int{1}
}

func (x *Report) GetAdvertisement() *Advertisement {
	if x != nil {
		return x.Advertisement
	}
	return nil
}

func (x *Report) GetTime() *Time {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Report) GetLocation() *LocationReport {
	if x != nil {
		return x.Location
	}
	return nil
}

type Advertisement struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	Identifier                  *Identifier            `protobuf:"bytes,5,opt,name=identifier,proto3" json:"identifier,omitempty"`
	UnwantedTrackingModeEnabled uint32                 `protobuf:"varint,6,opt,name=unwantedTrackingModeEnabled,proto3" json:"unwantedTrackingModeEnabled,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Advertisement) Reset() {
	*x = Advertisement{}
	mi := &file_findhub_locationreportupload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Advertisement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Advertisement) ProtoMessage() {}

func (x *Advertisement) ProtoReflect() protoreflect.Message {
	mi := &file_findhub_locationreportupload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Advertisement.ProtoReflect.Descriptor instead.
func (*Advertisement) Descriptor() ([]byte, []int) {
	return file_findhub_locationreportupload_proto_rawDescGZIP(), []int{2}
}

func (x *Advertisement) GetIdentifier() *Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *Advertisement) GetUnwantedTrackingModeEnabled() uint32 {
	if x != nil {
		return x.UnwantedTrackingModeEnabled
	}
	return 0
}

type Identifier struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TruncatedEid    []byte                 `protobuf:"bytes,6,opt,name=truncatedEid,proto3" json:"truncatedEid,omitempty"`
	CanonicDeviceId []byte                 `protobuf:"bytes,7,opt,name=canonicDeviceId,proto3" json:"canonicDeviceId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Identifier) Reset() {
	*x = Identifier{}
	mi := &file_findhub_locationreportupload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identifier) ProtoMessage() {}

func (x *Identifier) ProtoReflect() protoreflect.Message {
	mi := &file_findhub_locationreportupload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identifier.ProtoReflect.Descriptor instead.
func (*Identifier) Descriptor() ([]byte, []int) {
	return file_findhub_locationreportupload_proto_rawDescGZIP(), []int{3}
}

func (x *Identifier) GetTruncatedEid() []byte {
	if x != nil {
		return x.TruncatedEid
	}
	return nil
}

func (x *Identifier) GetCanonicDeviceId() []byte {
	if x != nil {
		return x.CanonicDeviceId
	}
	return nil
}

type ClientMetadata struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Version       *ClientVersionInformation `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMetadata) Reset() {
	*x = ClientMetadata{}
	mi := &file_findhub_locationreportupload_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMetadata) ProtoMessage() {}

func (x *ClientMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_findhub_locationreportupload_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMetadata.ProtoReflect.Descriptor instead.
func (*ClientMetadata) Descriptor() ([]byte, []int) {
	return file_findhub_locationreportupload_proto_rawDescGZIP(), []int{4}
}

func (x *ClientMetadata) GetVersion() *ClientVersionInformation {
	if x != nil {
		return x.Version
	}
	return nil
}

type ClientVersionInformation struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PlayServicesVersion string                 `protobuf:"bytes,1,opt,name=playServicesVersion,proto3" json:"playServicesVersion,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ClientVersionInformation) Reset() {
	*x = ClientVersionInformation{}
	mi := &file_findhub_locationreportupload_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientVersionInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientVersionInformation) ProtoMessage() {}

func (x *ClientVersionInformation) ProtoReflect() protoreflect.Message {
	mi := &file_findhub_locationreportupload_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientVersionInformation.ProtoReflect.Descriptor instead.
func (*ClientVersionInformation) Descriptor() ([]byte, []int) {
	return file_findhub_locationreportupload_proto_rawDescGZIP(), []int{5}
}

func (x *ClientVersionInformation) GetPlayServicesVersion() string {
	if x != nil {
		return x.PlayServicesVersion
	}
	return ""
}

var File_findhub_locationreportupload_proto protoreflect.FileDescriptor

const file_findhub_locationreportupload_proto_rawDesc = "" +
	"\n" +
	"\"findhub/locationreportupload.proto\x1a\x14findhub/common.proto\"\xa7\x01\n" +
	"\x15LocationReportsUpload\x12!\n" +
	"\areports\x18\x01 \x03(\v2\a.ReportR\areports\x127\n" +
	"\x0eclientMetadata\x18\x02 \x01(\v2\x0f.ClientMetadataR\x0eclientMetadata\x12\x18\n" +
	"\arandom1\x18\x03 \x01(\x04R\arandom1\x12\x18\n" +
	"\arandom2\x18\x04 \x01(\x04R\arandom2\"\x86\x01\n" +
	"\x06Report\x124\n" +
	"\radvertisement\x18\x01 \x01(\v2\x0e.AdvertisementR\radvertisement\x12\x19\n" +
	"\x04time\x18\x04 \x01(\v2\x05.TimeR\x04time\x12+\n" +
	"\blocation\x18\x06 \x01(\v2\x0f.LocationReportR\blocation\"~\n" +
	"\rAdvertisement\x12+\n" +
	"\n" +
	"identifier\x18\x05 \x01(\v2\v.IdentifierR\n" +
	"identifier\x12@\n" +
	"\x1bunwantedTrackingModeEnabled\x18\x06 \x01(\rR\x1bunwantedTrackingModeEnabled\"Z\n" +
	"\n" +
	"Identifier\x12\"\n" +
	"\ftruncatedEid\x18\x06 \x01(\fR\ftruncatedEid\x12(\n" +
	"\x0fcanonicDeviceId\x18\a \x01(\fR\x0fcanonicDeviceId\"E\n" +
	"\x0eClientMetadata\x123\n" +
	"\aversion\x18\x02 \x01(\v2\x19.ClientVersionInformationR\aversion\"L\n" +
	"\x18ClientVersionInformation\x120\n" +
	"\x13playServicesVersion\x18\x01 \x01(\tR\x13playServicesVersionBRZPgithub.com/mheers/google-find-my-tools-go/pkg/googlefindmy/proto/findhub;findhubb\x06proto3"

var (
	file_findhub_locationreportupload_proto_rawDescOnce sync.Once
	file_findhub_locationreportupload_proto_rawDescData []byte
)

func file_findhub_locationreportupload_proto_rawDescGZIP() []byte {
	file_findhub_locationreportupload_proto_rawDescOnce.Do(func() {
		file_findhub_locationreportupload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_findhub_locationreportupload_proto_rawDesc), len(file_findhub_locationreportupload_proto_rawDesc)))
	})
	return file_findhub_locationreportupload_proto_rawDescData
}

var file_findhub_locationreportupload_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_findhub_locationreportupload_proto_goTypes = []any{
	(*LocationReportsUpload)(nil),    // 0: LocationReportsUpload
	(*Report)(nil),                   // 1: Report
	(*Advertisement)(nil),            // 2: Advertisement
	(*Identifier)(nil),               // 3: Identifier
	(*ClientMetadata)(nil),           // 4: ClientMetadata
	(*ClientVersionInformation)(nil), // 5: ClientVersionInformation
	(*Time)(nil),                     // 6: Time
	(*LocationReport)(nil),           // 7: LocationReport
}
var file_findhub_locationreportupload_proto_depIdxs = []int32{
	1, // 0: LocationReportsUpload.reports:type_name -> Report
	4, // 1: LocationReportsUpload.clientMetadata:type_name -> ClientMetadata
	2, // 2: Report.advertisement:type_name -> Advertisement
	6, // 3: Report.time:type_name -> Time
	7, // 4: Report.location:type_name -> LocationReport
	3, // 5: Advertisement.identifier:type_name -> Identifier
	5, // 6: ClientMetadata.version:type_name -> ClientVersionInformation
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_findhub_locationreportupload_proto_init() }
func file_findhub_locationreportupload_proto_init() {
	if File_findhub_locationreportupload_proto != nil {
		return
	}
	file_findhub_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_findhub_locationreportupload_proto_rawDesc), len(file_findhub_locationreportupload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_findhub_locationreportupload_proto_goTypes,
		DependencyIndexes: file_findhub_locationreportupload_proto_depIdxs,
		MessageInfos:      file_findhub_locationreportupload_proto_msgTypes,
	}.Build()
	File_findhub_locationreportupload_proto = out.File
	file_findhub_locationreportupload_proto_goTypes = nil
	file_findhub_locationreportupload_proto_depIdxs = nil
}
